- repo-list:
  - name: neverthrow
    repo: supermacro/neverthrow
    ref: "de73e225d76bddadec1f2e1c86ec91996f8087a9"
    path: "README.md"
  - name: valibot
    repo: fabian-hiller/valibot
    ref: "3833d69d3b3a383693000410d40f1b504f446170"
    sparse-checkout:
      paths: "website/src/routes/guides"
    path: "website/src/routes/guides/**/*.{md,mdx}"
  - name: next.js
    repo: vercel/next.js
    ref: "138c9ae62a78f699570b04be0c6132a4ad9606a8"
    sparse-checkout:
      paths: "docs"
    path: "docs/**/*.{md,mdx}"
    path-meta:
      options:
        - "--toml-engine"
        - "smol-toml"
